requires 'Getopt::Long';
requires 'HTML5::DOM';
requires 'Progress::Any';
requires 'Progress::Any::Output';
requires 'Progress::Any::Output::TermProgressBarColor';
requires 'URI::Escape';
requires 'WWW::Mechanize';
	